-- AardwolfMudlet: Script Loader
-- Auto-generated during refactoring. Loads all modules in dependency order.
--
-- DO NOT EDIT THIS FILE DIRECTLY. Regenerate from manifest.json.

local base = getMudletHomeDir() .. "/aardwolf/scripts"

-- ============================================================
-- Core initialization
-- ============================================================
aard = aard or {}
aard.version = "0.2.0-refactor"

-- Setup logging
aard.log = aard.log or {}
function aard.log:info(msg)
    echo("[aard] " .. tostring(msg) .. "\n")
end

function aard.log:debug(msg)
    -- echo("[aard:debug] " .. tostring(msg) .. "\n")
end

function aard.log:error(msg)
    echo("[aard:ERROR] " .. tostring(msg) .. "\n")
end

-- Core modules (ordered by dependency)
local core_modules = {
    { path = base .. "/core/__init__.lua",          name = "aard (group init)" },
    { path = base .. "/core/onsysdatasendrequest.lua", name = "onSysDataSendRequest" },
    { path = base .. "/core/cssman.lua",            name = "CSSMan" },
    { path = base .. "/core/tablekeydelete.lua",    name = "TableKeyDelete" },
    { path = base .. "/core/config.lua",            name = "config" },
    { path = base .. "/core/guiframe.lua",          name = "guiFrame" },
    { path = base .. "/core/guiload.lua",           name = "guiLoad" },
    { path = base .. "/core/oningame.lua",          name = "onInGame" },
    { path = base .. "/tracking/__init__.lua",      name = "adt (group init)" },
    { path = base .. "/tracking/adt_pup_level_death.lua", name = "adt pup level death" },
    { path = base .. "/mapper/__init__.lua",        name = "aardMap (group init)" },
    { path = base .. "/mapper/init_map.lua",        name = "init_map" },
    { path = base .. "/mapper/labeladjustment.lua", name = "labelAdjustment" },
    { path = base .. "/mapper/tools.lua",           name = "tools" },
    { path = base .. "/mapper/mapaddons.lua",       name = "mapAddons" },
    { path = base .. "/mapper/rooms.lua",           name = "rooms" },
    { path = base .. "/mapper/speedwalk.lua",       name = "speedwalk" },
    { path = base .. "/mapper/areas.lua",           name = "areas" },
    { path = base .. "/mapper/exits.lua",           name = "exits" },
    { path = base .. "/mapper/sectors.lua",         name = "sectors" },
    { path = base .. "/mapper/areaindex.lua",       name = "areaIndex" },
    { path = base .. "/mapper/coordrun.lua",        name = "coordrun" },
    { path = base .. "/mapper/questinfo.lua",       name = "questinfo" },
    { path = base .. "/gmcp/onchannel.lua",         name = "onChannel" },
    { path = base .. "/gmcp/onsectors.lua",         name = "onSectors" },
    { path = base .. "/gmcp/onstatus.lua",          name = "onStatus" },
    { path = base .. "/gmcp/ongroup.lua",           name = "onGroup" },
    { path = base .. "/gmcp/onquest.lua",           name = "onQuest" },
    { path = base .. "/gmcp/onvitals.lua",          name = "onVitals" },
    { path = base .. "/gmcp/onroom.lua",            name = "onRoom" },
    { path = base .. "/gmcp/ontick.lua",            name = "onTick" },
    { path = base .. "/gmcp/onname.lua",            name = "onName" },
    { path = base .. "/gui/__init__.lua",           name = "favMenu (group init)" },
    { path = base .. "/gui/flyout.lua",             name = "flyout" },
}

for _, mod in ipairs(core_modules) do
    local ok, err = pcall(dofile, mod.path)
    if not ok then
        echo("[aard:ERROR] Failed to load " .. mod.name .. ": " .. tostring(err) .. "\n")
    end
end

echo("[aard] Scripts loaded. Version: " .. (aard.version or "unknown") .. "\n")
