-- AardwolfMudlet: areaIndex
-- Group: aard > aardMap

aard.areaInfo = {
["A Bad Trip"]={zone="badtrip",min=0,max=0},
["Alagh, the Blood Lands"]={zone="alagh",min=0,max=0},
["Gelidus"]={zone="gelidus",min=0,max=0},
["The Continent of Mesolar"]={zone="mesolar",min=0,max=0},
["The Dark Continent, Abend"]={zone="abend",min=0,max=0},
["The Southern Ocean"]={zone="southern",min=0,max=0},
["The Uncharted Oceans"]={zone="uncharted",min=0,max=0},
["The Warzone"]={zone="warzone",min=0,max=0},
["Vidblain, the Ever Dark"]={zone="vidblain",min=0,max=0},
["The Grand City of Aylor"]={zone="aylor",min=1,max=201},
["The Aylorian Academy"]={zone="academy",min=1,max=201},
["Kimr's Farm"]={zone="farm",min=1,max=5},
["Lowlands Paradise '96"]={zone="lowlands",min=1,max=5},
["The Forest of Li'Dnesh"]={zone="lidnesh",min=1,max=10},
["The Path of the Believer"]={zone="believer",min=1,max=10},
["Tournament Camps"]={zone="camps",min=1,max=10},
["Art of Melody"]={zone="melody",min=1,max=15},
["The Call of Heroes"]={zone="callhero",min=1,max=15},
["Hotel Orlando"]={zone="orlando",min=1,max=20},
["Land of Legend"]={zone="legend",min=1,max=20},
["Sen'narre Lake"]={zone="sennarre",min=1,max=20},
["The Land of the Beer Goblins"]={zone="beer",min=1,max=20},
["Gallows Hill"]={zone="gallows",min=1,max=30},
["Jotunheim"]={zone="jotun",min=1,max=40},
["Chaprenula's Laboratory"]={zone="lab",min=5,max=15},
["Siren's Oasis Resort"]={zone="sirens",min=5,max=15},
["The Fire Swamp"]={zone="fireswamp",min=5,max=15},
["The First Ascent"]={zone="ascent",min=5,max=15},
["The Graveyard"]={zone="graveyard",min=5,max=15},
["Den of Thieves"]={zone="thieves",min=5,max=20},
["Giant's Pet Store"]={zone="petstore",min=5,max=20},
["Sundered Vale"]={zone="vale",min=5,max=20},
["The Amusement Park"]={zone="amusement",min=5,max=20},
["The Chessboard"]={zone="chessboard",min=5,max=20},
["Child's Play"]={zone="childsplay",min=5,max=25},
["Dortmund"]={zone="dortmund",min=5,max=25},
["Canyon Memorial Hospital"]={zone="canyon",min=5,max=30},
["Fantasy Fields"]={zone="fantasy",min=5,max=30},
["Kerofk"]={zone="kerofk",min=5,max=30},
["The Gauntlet"]={zone="gauntlet",min=5,max=30},
["The Wood Elves of Nalondir"]={zone="woodelves",min=5,max=30},
["A Magical Hodgepodge"]={zone="hodgepodge",min=5,max=35},
["Aardwolf Zoological Park"]={zone="zoo",min=5,max=35},
["Brightsea and Glimmerdim"]={zone="glimmerdim",min=5,max=35},
["Cloud City of Gnomalin"]={zone="gnomalin",min=5,max=35},
["Olde Worlde Carnivale"]={zone="carnivale",min=5,max=35},
["The Infestation"]={zone="infest",min=5,max=35},
["The Shadows of Minos"]={zone="minos",min=5,max=35},
["The Town of Solan"]={zone="solan",min=5,max=35},
["War of the Wizards"]={zone="wizards",min=5,max=35},
["Hatchling Aerie"]={zone="hatchling",min=5,max=45},
["Adventures in Sendhia"]={zone="sendhian",min=5,max=50},
["Swordbreaker's Hoard"]={zone="hoard",min=5,max=50},
["The Chasm and The Catacombs"]={zone="chasm",min=10,max=20},
["Warrior's Training Camp"]={zone="wtc",min=10,max=20},
["All in a Fayke Day"]={zone="fayke",min=10,max=30},
["Guardian's Spyre of Knowledge"]={zone="spyreknow",min=10,max=30},
["Sho'aram, Castle in the Sand"]={zone="sandcastle",min=10,max=30},
["Fort Terramire"]={zone="terramire",min=10,max=35},
["New Thalos"]={zone="newthalos",min=10,max=35},
["Storm Mountain"]={zone="storm",min=10,max=35},
["Jungles of Verume"]={zone="verume",min=10,max=40},
["Wildwood"]={zone="wildwood",min=10,max=40},
["Dhal'Gora Outlands"]={zone="dhalgora",min=10,max=50},
["The Temple of Shouggoth"]={zone="shouggoth",min=10,max=50},
["Keep of the Kobaloi"]={zone="kobaloi",min=10,max=201},
["Aerial City of Cineko"]={zone="cineko",min=15,max=30},
["Kul Tiras"]={zone="kultiras",min=15,max=30},
["Necromancers' Guild"]={zone="necro",min=15,max=30},
["The UnderDark"]={zone="underdark",min=15,max=50},
["Realm of the Zodiac"]={zone="zodiac",min=20,max=30},
["Atlantis"]={zone="atlantis",min=20,max=40},
["Death's Manor"]={zone="manor",min=20,max=40},
["The Fractured Lands"]={zone="fractured",min=20,max=40},
["Weather Observatory"]={zone="weather",min=20,max=40},
["The Maelstrom"]={zone="maelstrom",min=20,max=45},
["Ancient Greece"]={zone="greece",min=20,max=50},
["Kingdom of Ahner"]={zone="ahner",min=20,max=50},
["Thandeld's Conflict"]={zone="conflict",min=20,max=50},
["Sheila's Cat Sanctuary"]={zone="cats",min=25,max=35},
["Mudwog's Swamp"]={zone="mudwog",min=30,max=40},
["Cradlebrook"]={zone="cradle",min=30,max=50},
["The Coral Kingdom"]={zone="coral",min=30,max=50},
["The Labyrinth"]={zone="labyrinth",min=30,max=60},
["Kingsholm"]={zone="kingsholm",min=30,max=65},
["Gold Rush"]={zone="goldrush",min=30,max=70},
["The Imperial City of Reme"]={zone="reme",min=30,max=100},
["The Silver Volcano"]={zone="volcano",min=30,max=100},
["Descent to Hell"]={zone="hell",min=35,max=55},
["Onyx Bazaar"]={zone="bazaar",min=35,max=55},
["The Blighted Tundra of Andarin"]={zone="andarin",min=35,max=60},
["Diamond Soul Revelation"]={zone="dsr",min=35,max=85},
["The Great Salt Flats"]={zone="salt",min=40,max=50},
["Raganatittu"]={zone="raga",min=40,max=60},
["The Darkside of the Fractured Lands"]={zone="darkside",min=40,max=60},
["The Wobbly Woes of Woobleville"]={zone="wooble",min=40,max=60},
["Zangar's Demonic Grotto"]={zone="zangar",min=40,max=60},
["The Land of Oz"]={zone="landofoz",min=40,max=70},
["Paradise Lost"]={zone="paradise",min=50,max=70},
["The Flying Citadel"]={zone="citadel",min=50,max=70},
["Castle Vlad-Shamir"]={zone="vlad",min=50,max=80},
["Earth Plane 4"]={zone="earthplane",min=50,max=80},
["The Old Cathedral"]={zone="cathedral",min=50,max=80},
["Jenny's Tavern"]={zone="jenny",min=50,max=100},
["Storm Ships of Lem-Dagor"]={zone="lemdagor",min=50,max=100},
["The Yurgach Domain"]={zone="yurgach",min=50,max=100},
["Hedgehogs' Paradise"]={zone="hedge",min=60,max=80},
["Plains of Nulan'Boar"]={zone="nulan",min=60,max=80},
["The Goblin Fortress"]={zone="fortress",min=60,max=80},
["The Great City of Knossos"]={zone="knossos",min=60,max=80},
["The Killing Fields"]={zone="fields",min=60,max=80},
["The Palace of Song"]={zone="songpalace",min=60,max=80},
["The Three Pillars of Diatz"]={zone="diatz",min=60,max=80},
["Realm of Deneria"]={zone="deneria",min=60,max=85},
["The DarkLight"]={zone="darklight",min=60,max=120},
["The Ruins of Diamond Reach"]={zone="ruins",min=60,max=120},
["Rosewood Castle"]={zone="rosewood",min=60,max=150},
["Imperial Nation"]={zone="imperial",min=65,max=201},
["Aardington Estate"]={zone="aardington",min=70,max=90},
["The Tournament of Illoria"]={zone="illoria",min=70,max=90},
["Wayward Alehouse"]={zone="alehouse",min=70,max=90},
["Nenukon and the Far Country"]={zone="nenukon",min=70,max=100},
["The Relinquished Tombs"]={zone="tombs",min=70,max=100},
["Tai'rha Laym"]={zone="laym",min=70,max=110},
["The Empire of Talsa"]={zone="talsa",min=70,max=130},
["The Fabled City of Stone"]={zone="stone",min=70,max=130},
["Northstar"]={zone="northstar",min=70,max=140},
["Kobold Siege Camp"]={zone="siege",min=80,max=100},
["Snuckles Village"]={zone="snuckles",min=80,max=100},
["The Gladiator's Arena"]={zone="arena",min=80,max=100},
["The Realm of the Hawklords"]={zone="hawklord",min=80,max=100},
["Wedded Bliss"]={zone="bliss",min=80,max=100},
["Anthrox"]={zone="anthrox",min=80,max=110},
["Island of Lost Time"]={zone="losttime",min=80,max=110},
["Realm of the Firebird"]={zone="firebird",min=80,max=110},
["Deathtrap Dungeon"]={zone="deathtrap",min=80,max=130},
["Pompeii"]={zone="pompeii",min=90,max=110},
["The Scarred Lands"]={zone="scarred",min=90,max=110},
["The Monastery"]={zone="monastery",min=90,max=120},
["Dark Elf Stronghold"]={zone="stronghold",min=90,max=125},
["Elemental Chaos"]={zone="elemental",min=90,max=150},
["Halls of the Damned"]={zone="damned",min=95,max=115},
["Insanitaria"]={zone="insan",min=95,max=115},
["Ascension Bluff Nursing Home"]={zone="nursing",min=100,max=120},
["Dusk Valley"]={zone="duskvalley",min=100,max=120},
["Faerie Tales"]={zone="ft1",min=100,max=120},
["Seven Wonders"]={zone="wonders",min=100,max=120},
["Xyl's Mosaic"]={zone="xylmos",min=100,max=120},
["Masquerade Island"]={zone="masq",min=100,max=130},
["Into the Long Night"]={zone="longnight",min=100,max=200},
["Sanctity of Eternal Damnation"]={zone="sanctity",min=100,max=201},
["Gnoll's Quarry"]={zone="quarry",min=105,max=125},
["The Marshlands of Agroth"]={zone="agroth",min=105,max=125},
["Arboretum"]={zone="arboretum",min=110,max=130},
["Tairayden Peninsula"]={zone="peninsula",min=110,max=130},
["The Stuff of Shadows"]={zone="stuff",min=110,max=130},
["Living Mines of Dak'Tai"]={zone="livingmine",min=110,max=140},
["Christmas Vacation"]={zone="xmas",min=110,max=150},
["The Misty Shores of Yarr"]={zone="yarr",min=115,max=135},
["Gilda And The Dragon"]={zone="gilda",min=120,max=140},
["The Eighteenth Dynasty"]={zone="dynasty",min=120,max=140},
["The Sanguine Tavern"]={zone="sanguine",min=120,max=140},
["Verdure Estate"]={zone="verdure",min=120,max=140},
["The Slaughter House"]={zone="slaughter",min=120,max=145},
["Faerie Tales II"]={zone="ftii",min=120,max=150},
["House of Cards"]={zone="cards",min=120,max=150},
["The Archipelago of Entropy"]={zone="entropy",min=120,max=150},
["The Uprising"]={zone="uprising",min=120,max=160},
["The Broken Halls of Horath"]={zone="horath",min=120,max=170},
["The School of Horror"]={zone="sohtwo",min=120,max=175},
["The Amazon Nation"]={zone="amazon",min=120,max=201},
["Tumari's Diner"]={zone="diner",min=125,max=145},
["The Blood Opal of Rauko'ra"]={zone="raukora",min=125,max=201},
["The School of Horror"]={zone="sohtwo",min=125,max=201},
["Foolish Promises"]={zone="promises",min=130,max=140},
["The Dark Temple of Zyian"]={zone="zyian",min=130,max=150},
["The Drageran Empire"]={zone="drageran",min=130,max=150},
["Tir na nOg"]={zone="tirna",min=130,max=150},
["A Peaceful Giant Village"]={zone="village",min=130,max=160},
["The Reman Conspiracy"]={zone="remcon",min=130,max=170},
["The Mountains of Desolation"]={zone="desolation",min=130,max=175},
["The Desert Prison"]={zone="desert",min=130,max=201},
["Desert Doom"]={zone="ddoom",min=135,max=150},
["Imagi's Nation"]={zone="imagi",min=140,max=160},
["Nanjiki Ruins"]={zone="nanjiki",min=140,max=160},
["The Abyssal Caverns of Sahuagin"]={zone="sahuagin",min=140,max=160},
["The Cougarian Queendom"]={zone="cougarian",min=140,max=160},
["The Gathering Horde"]={zone="gathering",min=140,max=170},
["Unearthly Bonds"]={zone="bonds",min=140,max=170},
["The Empire of Aiighialla"]={zone="empire",min=140,max=180},
["Takeda's Warcamp"]={zone="takeda",min=140,max=201},
["Arisian Realm"]={zone="arisian",min=150,max=170},
["Winterlands"]={zone="winter",min=150,max=170},
["Battlefields of Adaldar"]={zone="adaldar",min=150,max=180},
["Sagewood Grove"]={zone="sagewood",min=150,max=180},
["Rebellion of the Nix"]={zone="rebellion",min=150,max=190},
["The Cataclysm"]={zone="cataclysm",min=150,max=201},
["The Ruins of Stormhaven"]={zone="stormhaven",min=150,max=201},
["Black Lagoon"]={zone="lagoon",min=155,max=195},
["Annwn"]={zone="annwn",min=160,max=180},
["Dread Tower"]={zone="dread",min=160,max=180},
["Helegear Sea"]={zone="helegear",min=160,max=180},
["The Covenant of Mistridge"]={zone="mistridge",min=160,max=201},
["The Witches of Omen Tor"]={zone="omentor",min=160,max=201},
["Tribal Origins"]={zone="origins",min=165,max=190},
["Avian Kingdom"]={zone="avian",min=170,max=190},
["Empyrean, Streets of Downfall"]={zone="empyrean",min=170,max=200},
["Eternal Autumn"]={zone="autumn",min=170,max=201},
["The Glamdursil"]={zone="glamdursil",min=170,max=201},
["The Tree of Life"]={zone="tol",min=170,max=201},
["Black Rose"]={zone="blackrose",min=175,max=201},
["Intrigues of Times Past"]={zone="times",min=175,max=201},
["Mount duNoir"]={zone="dunoir",min=175,max=201},
["The Deadlights"]={zone="deadlights",min=175,max=201},
["The Keep of Kearvek"]={zone="kearvek",min=175,max=201},
["Artificer's Mayhem"]={zone="mayhem",min=180,max=201},
["The Partroxis"]={zone="partroxis",min=180,max=201},
["Tanra'vea"]={zone="tanra",min=180,max=201},
["The Astral Travels"]={zone="astral",min=180,max=201},
["The Blood Sanctum"]={zone="sanctum",min=180,max=201},
["The Temple of Shal'indrael"]={zone="temple",min=180,max=201},
["Yggdrasil: The World Tree"]={zone="ygg",min=180,max=201},
["Kiksaadi Cove"]={zone="cove",min=190,max=200},
["Entrance to Hades"]={zone="hades",min=190,max=201},
["Nottingham"]={zone="nottingham",min=190,max=201},
["The Council of the Wyrm"]={zone="wyrm",min=190,max=201},
["The Icy Caldera of Mauldoon"]={zone="caldera",min=190,max=201},
["The Trouble with Gwillimberry"]={zone="gwillim",min=190,max=201},
["Crynn's Church"]={zone="crynn",min=195,max=201},
["Umari's Castle"]={zone="umari",min=195,max=201},
["A Genie's Last Wish"]={zone="geniewish",min=200,max=201},
["Afterglow"]={zone="afterglow",min=200,max=201},
["Andolor's Ocean Adventure Park"]={zone="oceanpark",min=200,max=201},
["Gypsy Caravan"]={zone="caravan",min=200,max=201},
["Icefall"]={zone="icefall",min=200,max=201},
["Journey to the Inferno"]={zone="inferno",min=200,max=201},
["Ketu Uplands"]={zone="ketu",min=200,max=201},
["Nebulous Horizon"]={zone="horizon",min=200,max=201},
["Oradrin's Chosen"]={zone="oradrin",min=200,max=201},
["Realm of the Sacred Flame"]={zone="firenation",min=200,max=201},
["The Cracks of Terra"]={zone="terra",min=200,max=201},
["The Earth Lords"]={zone="earthlords",min=200,max=201},
["The Nyne Woods"]={zone="nynewoods",min=200,max=201},
["The Titans' Keep"]={zone="titan",min=200,max=201},
["The Were Wood"]={zone="werewood",min=200,max=201},
["Qong"]={zone="qong",min=200,max=220},
["Crossroads of Fortune"]={zone="fortune",min=201,max=201},
["Ookushka Garrison"]={zone="ooku",min=201,max=201},
["Radiance Woods"]={zone="radiance",min=201,max=201},
["The Curse of the Midnight Fens"]={zone="fens",min=201,max=201},
["The Dungeon of Doom"]={zone="dundoom",min=201,max=201},
["The Realm of Infamy"]={zone="infamy",min=201,max=201},
["Winds of Fate"]={zone="winds",min=201,max=201},
["A Clearing in the Woods"]={zone="romani",min=210,max=210},
["Cathedral of the Elements"]={zone="cabal",min=210,max=210},
["Dark Temple of Zhamet"]={zone="rhabdo",min=210,max=210},
["Disciples of Hassan Clan Hall"]={zone="doh",min=210,max=210},
["Dominion Clan Area"]={zone="dominion",min=210,max=210},
["Isle of Anglesey"]={zone="druid",min=210,max=210},
["Loqui Clan Area"]={zone="loqui",min=210,max=210},
["Masaki Clan Area"]={zone="masaki",min=210,max=210},
["Midgaardian Publishing House"]={zone="gaardian",min=210,max=210},
["Perdition Clan Area"]={zone="perdition",min=210,max=210},
["The Bard Clan"]={zone="bard",min=210,max=210},
["The Boot Camp"]={zone="bootcamp",min=210,max=210},
["The Collective Mind of Tao"]={zone="tao",min=210,max=210},
["The Crimson Horde Clan Hall"]={zone="crimson",min=210,max=210},
["The Crusader Clan"]={zone="crusaders",min=210,max=210},
["The Emerald Clan HQ"]={zone="emerald",min=210,max=210},
["The Fortress of Knowledge"]={zone="seekers",min=210,max=210},
["The Halls of Retribution"]={zone="retri",min=210,max=210},
["The Halls of Vanir"]={zone="vanir",min=210,max=210},
["The Ivory City"]={zone="amazonclan",min=210,max=210},
["The Legendary City of Tanelorn"]={zone="tanelorn",min=210,max=210},
["The Order of Light"]={zone="light",min=210,max=210},
["The Realm of Chaos"]={zone="chaos",min=210,max=210},
["The S.S. Hook"]={zone="hook",min=210,max=210},
["The Shadokil Guildhouse"]={zone="shadokil",min=210,max=210},
["The Stronghold of the Imperium Clan"]={zone="imperium",min=210,max=210},
["The Twinlobe Clan HQ"]={zone="twinlobe",min=210,max=210},
["The Underground Hall"]={zone="daoine",min=210,max=210},
["The White Dragon Clan"]={zone="dragon",min=210,max=210},
["The World of the Watchmen"]={zone="watchmen",min=210,max=210},
["The Xunti Cult"]={zone="xunti",min=210,max=210},
["Touchstone Cavern"]={zone="touchstone",min=210,max=210},
["Twilight Hall"]={zone="pyre",min=210,max=210},
["Immortal Homes"]={zone="immhomes",min=0,max=0},
["Aardwolf Estates 2000"]={zone="manor3",min=0,max=0},
["Prairie Village Estates"]={zone="manorville",min=0,max=0},
["Shady Acres Estates"]={zone="manorwoods",min=0,max=0},
["The Aardwolf Real Estates"]={zone="manor1",min=0,max=0},
["Mountain View Estates"]={zone="manormount",min=0,max=0},
["The Aardwolf Isle Estates"]={zone="manorisle",min=0,max=0},
["Seaside Height Estates"]={zone="manorsea",min=0,max=0},
}

--the Table below is created as a reverse index, swapping the fullname and short zone name so that reverse lookups can be performed easily.
aard.areaIndex = {}
for i, areaName in pairs(aard.areaInfo) do
	aard.areaIndex[areaName.zone] = {zone=i,min=areaName.min,max=areaName.max}
end
